# Makefile for 1_* in this dir.caption0 .
# Written by N.Aoki, HCU
# 2021/03/11 ver1.0

CC=gcc
CFLAGS=-Wall -03

all: 1_1 1_2 1_3 1_4 1_5 1_6 1_7 1_8 1_9 1_10
all_s: 1_1s 1_2s 1_3s 1_4s 1_5s 1_6s 1_7s 1_8s 1_9s 1_10s

# default
1_1: 1_1.c
	$(CC) 1_1.c -o 1_1 -Wall
1_2: 1_2.c
	$(CC) 1_2.c -o 1_2 -Wall
1_3: 1_3.c
	$(CC) 1_3.c -o 1_3 -Wall
1_4: 1_4.c
	$(CC) 1_4.c -o 1_4 -Wall
1_5: 1_5.c
	$(CC) 1_5.c -o 1_5 -Wall
1_6: 1_6.c
	$(CC) 1_6.c -o 1_6 -Wall
1_7: 1_7.c
	$(CC) 1_7.c -o 1_7 -Wall
1_8: 1_8.c
	$(CC) 1_8.c -o 1_8 -Wall
1_9: 1_9.c
	$(CC) 1_9.c -o 1_9 -Wall
1_10: 1_10.c
	$(CC) 1_10.c -o 1_10 -Wall

# optimization
1_1s: 1_1.c
	$(CC) 1_1.c -o 1_1 $(CFLAGS)
1_2s: 1_2.c
	$(CC) 1_2.c -o 1_2 $(CFLAGS)
1_3s: 1_3.c
	$(CC) 1_3.c -o 1_3 $(CFLAGS)
1_4s: 1_4.c
	$(CC) 1_4.c -o 1_4 $(CFLAGS)
1_5s: 1_5.c
	$(CC) 1_5.c -o 1_5 $(CFLAGS)
1_6s: 1_6.c
	$(CC) 1_6.c -o 1_6 $(CFLAGS)
1_7s: 1_7.c
	$(CC) 1_7.c -o 1_7 $(CFLAGS)
1_8s: 1_8.c
	$(CC) 1_8.c -o 1_8 $(CFLAGS)
1_9s: 1_9.c
	$(CC) 1_9.c -o 1_9 $(CFLAGS)
1_10s: 1_10.c
	$(CC) 1_10.c -o 1_10 $(CFLAGS)

clean:
	rm -f 1_1 1_2 1_3 1_4 1_5 1_6 1_7 1_8 1_9 1_10
	rm -f 1_1s 1_2s 1_3s 1_4s 1_5s 1_6s 1_7s 1_8s 1_9s 1_10s
